# Week 4: Data Frames

**Conditioning and Subsetting**
    - Syntax: dataframe[rows, columns]

**New columns/rows**

**Excercise:**
    - Create a clone of an existing data frame (or create your own if time permits)
    - Manipulate the data frame by adding new and old columns/rows
    - Sorting your data frame
    
**Helpful functions**
    - head(), summary(), glimpse(), is.na(), ...
    
**Excercise:**
    - Use these newly learned functions to find specific information in your data frame

## Data Frames: 


This week, we will discover Data Frames--the fundamental data structure to deal with data sets!

A data frame is closely related to a list. In Layman terms, a data frame is a sub category of a list because it has multiple restrictions on how a data frame is defined; thus, it represents a list with the class, "data.frame". 


**Restrictions/Requirements for a Data Frame**

1) Components must consist of vectors, factors, numeric matrices, lists, or other data frames.

2) Matrices, lists, and data frames provide as many variables to the new data frame as they have columns, elements, or variables, respectively.

3) Numeric vectors, logicals, and factors are left alone. Character vectors are coerced to be factors, whose levels are the unique values appearing in the vector.

4) If you are adding vector structures to the data frame, it is important to note that *all vector structures* must be the SAME LENGTH! Similarly, *matrix structures* must all have the SAME ROW SIZE. 

**Why not use a matrix? Isn't this what a data frame basically is?**

Not necessarily! The main reason a data frame is so useful to manipulate datasets is to include numerics, characters, and other classes of objects. You may ask why not use a matrix. That's because a matrix does not have the versatility of a data frame in the sense that it can only hold *numbers*.

**Why?** 

A data frame may for many purposes be regarded as a matrix with columns possibly of
differing modes and attributes. It may be displayed in matrix form, and its rows and columns
extracted using matrix indexing conventions.

## Creating a Data Frame


Keep in mind that a data frame is basically just a data set! Examples of where data sets imported from include CSV files, relational databases, and software packages. 

However, what if you want to create a data frame from scratch using the amazing R programming langauge??
**Use the function**, ' <code>data.frame()</code> '.


Now, consider a scenario where you have 3 vectors and you want to compose a data from from them. Below, you will notice a three vectors: forecast (description of the weather in words), low_temperature (what is the expected lowest temperature), and precipitation (whether or not it rains). 

**Notice how each vector contains various classes.** In this case, characters, numerics, and booleans respectively. Onward to making a data frame...

In [4]:
forecast <- c("showers", "cloudy", "cloudy", "rain", "rain")

low_temperature <- c(46, 34, 44, 55, 53)

precipitation <- c(TRUE, FALSE, FALSE, TRUE, TRUE)

data.frame(forecast, low_temperature, precipitation)

  forecast low_temperature precipitation
1 showers  46               TRUE
2 cloudy   34              FALSE
3 cloudy   44              FALSE
4 rain     55               TRUE
5 rain     53               TRUE

## Vocabulary

-The top horizontal line that starts with "forecast", is called the **header**. 

-Following the header, each horizontal how underneath it is called a **data row**.

-Each element is synonymous with a **cell**.

## Subscripting and Subsetting

- Subscripting is explicitly identifying an element, using numeric integers, from a data frame.

- Subsetting is assigning that subscripted element(s) to a variable.

## Three Ways to Subscript and Subset:

**If you know the row and column numbers, or names, this method is your best bet. You can also select multiple rows/columns using the ' : '.**
    
<code> 
    dataframe_name[row_number, col_number]
</code>



**If your perspective is to find values given a certain condition (eg >, <, !=, etc.), then this method is ideal.**
    
<code> 
    subset(my_df, subset = some_condition)
</code>



**If you want a whole column's value, and you know the column name, then use this method.**
    
<code>
    data_frame$column_name
</code>

## Some Useful Functions To Make Data Frames Easier To Deal With

**head(data_frame, n = number of rows returned)**
- head() ==> will return first 'n' rows starting from the beginning of the data frame.


**tail(data_frame, n = number of rows returned)**
- tail() ==> will return first 'n' rows starting from the end of the data frame.


**summary(data_frame)**
- summary() ==> a function that will produce a gist of the results of each individual header. Examples of the statistical summaries that will be outputted include: 
    - Minimum
    - 1st Quartile
    - Median
    - Mean
    - 3rd Quartile
    - Maximum

- However, the function invokes particular methods which depend on the class of the first argument.


**str(data_frame)**
- str() ==> an alternative to 'summary()'. Displays the internal **str**ucture of a data frame, or any other object placed in parentheses.


**glimpse(data_frame)**
- glimpse() ==> basically transposes (the rows become the columns and the                   columns become the rows) the data frame

- The header becomes vertically-orientated


**nrow(data_frame)**
- nrow() ==> gives you the **n**umber of **row**s in the data frame


**ncol(data_frame)**
- ncol() ==> gives you the **n**umber of **col**umns in the data frame


**dim(data_frame)**
- dim() ==> a combination of nrow and ncol. Outputs rows and wolumns respectively.

- **Note** dim(data_frame)[1] == nrow(data_frame)
- **Note** dim(data_frame)[2] == ncol(data_frame)


**colnames(car)**
- colnames() ==> outputs a vector of the header, or the **col**umn **names**


**rownames(car)**
- colnames() ==> outputs a vector of the **row** **names**


**cbind(data_frame)**
- cbind() ==> combines multiple data frames into a single data frame (extends the data frame horizontally)

- separate the each data frame with a comma (e.g.: cbind(x, y, z) )


**rbind(data_frame)**
- rbind() ==> combines multiple data frames into a single data frame (extends the data frame vertically)

- separate the each data frame with a comma (e.g.: rbind(x, y, z) )


**fix(data_frame)**
- fix() ==> easy way to access the data editor so you can fix whatever element in the data frame that you want to


**help(data_frame)**
- help() ==> gives you additional information about the given data frame  
     that is available in R documentation.

## Excercise (Try some on your own using RStudio!): 
- Create a clone of an existing data frame (or create your own if time permits)
- Manipulate the data frame by adding new and old columns/rows
- Sort your data frame

You can look up your own data frames on R studio by downloading packages or using the built in data frames pre-installed by R.

## Sample Package (mtcars)

In [ ]:
# mtcars is a built-in data frame in R. This data frame holds information
## about various cars and their specifications such as miles per gallon, 
### horespower, etc.
car <- mtcars # now you can write car instead of mtcars
car 

# Here we will use classes to identify, you guessed it, each class.
class(car)
class(11)
class(c(1,2,3,4,5))
class("11")

# useful functions (see descriptions above)
head(car)
tail(car)

summary(car)
str(car)
glimpse(car)

nrow(car)
ncol(car)
dim(car)
colnames(car)
rownames(car)

cbind(car, car, car)
rbind(car, car, car)

fix(car)
help(car)

# format: data_frame$vector
car$mpg
hp <- car$hp

# specifiying a range of desired elements
car[car$disp > 235, ]
car[car$disp > mean(car$disp), ]
car[car$disp > mean(car$disp) & (car$hp > 180), ]

## Expected Output (from code above)
If you inputted everything above correctly, you should see something like this in the console!

In [ ]:
> car <- mtcars

> car 
                     mpg cyl  disp  hp drat    wt  qsec vs
Mazda RX4           21.0   6 160.0 110 3.90 2.620 16.46  0
Mazda RX4 Wag       21.0   6 160.0 110 3.90 2.875 17.02  0
Datsun 710          22.8   4 108.0  93 3.85 2.320 18.61  1
Hornet 4 Drive      21.4   6 258.0 110 3.08 3.215 19.44  1
Hornet Sportabout   18.7   8 360.0 175 3.15 3.440 17.02  0
Valiant             18.1   6 225.0 105 2.76 3.460 20.22  1
Duster 360          14.3   8 360.0 245 3.21 3.570 15.84  0
Merc 240D           24.4   4 146.7  62 3.69 3.190 20.00  1
Merc 230            22.8   4 140.8  95 3.92 3.150 22.90  1
Merc 280            19.2   6 167.6 123 3.92 3.440 18.30  1
Merc 280C           17.8   6 167.6 123 3.92 3.440 18.90  1
Merc 450SE          16.4   8 275.8 180 3.07 4.070 17.40  0
Merc 450SL          17.3   8 275.8 180 3.07 3.730 17.60  0
Merc 450SLC         15.2   8 275.8 180 3.07 3.780 18.00  0
Cadillac Fleetwood  10.4   8 472.0 205 2.93 5.250 17.98  0
Lincoln Continental 10.4   8 460.0 215 3.00 5.424 17.82  0
Chrysler Imperial   14.7   8 440.0 230 3.23 5.345 17.42  0
Fiat 128            32.4   4  78.7  66 4.08 2.200 19.47  1
Honda Civic         30.4   4  75.7  52 4.93 1.615 18.52  1
Toyota Corolla      33.9   4  71.1  65 4.22 1.835 19.90  1
Toyota Corona       21.5   4 120.1  97 3.70 2.465 20.01  1
Dodge Challenger    15.5   8 318.0 150 2.76 3.520 16.87  0
AMC Javelin         15.2   8 304.0 150 3.15 3.435 17.30  0
Camaro Z28          13.3   8 350.0 245 3.73 3.840 15.41  0
Pontiac Firebird    19.2   8 400.0 175 3.08 3.845 17.05  0
Fiat X1-9           27.3   4  79.0  66 4.08 1.935 18.90  1
Porsche 914-2       26.0   4 120.3  91 4.43 2.140 16.70  0
Lotus Europa        30.4   4  95.1 113 3.77 1.513 16.90  1
Ford Pantera L      15.8   8 351.0 264 4.22 3.170 14.50  0
Ferrari Dino        19.7   6 145.0 175 3.62 2.770 15.50  0
Maserati Bora       15.0   8 301.0 335 3.54 3.570 14.60  0
Volvo 142E          21.4   4 121.0 109 4.11 2.780 18.60  1
                    am gear carb
Mazda RX4            1    4    4
Mazda RX4 Wag        1    4    4
Datsun 710           1    4    1
Hornet 4 Drive       0    3    1
Hornet Sportabout    0    3    2
Valiant              0    3    1
Duster 360           0    3    4
Merc 240D            0    4    2
Merc 230             0    4    2
Merc 280             0    4    4
Merc 280C            0    4    4
Merc 450SE           0    3    3
Merc 450SL           0    3    3
Merc 450SLC          0    3    3
Cadillac Fleetwood   0    3    4
Lincoln Continental  0    3    4
Chrysler Imperial    0    3    4
Fiat 128             1    4    1
Honda Civic          1    4    2
Toyota Corolla       1    4    1
Toyota Corona        0    3    1
Dodge Challenger     0    3    2
AMC Javelin          0    3    2
Camaro Z28           0    3    4
Pontiac Firebird     0    3    2
Fiat X1-9            1    4    1
Porsche 914-2        1    5    2
Lotus Europa         1    5    2
Ford Pantera L       1    5    4
Ferrari Dino         1    5    6
Maserati Bora        1    5    8
Volvo 142E           1    4    2

> 

> class(car)
[1] "data.frame"
> class(11)
[1] "numeric"
> class(c(1,2,3,4,5))
[1] "numeric"
> class("11")
[1] "character"

> 

> head(car)
                   mpg cyl disp  hp drat    wt  qsec vs am
Mazda RX4         21.0   6  160 110 3.90 2.620 16.46  0  1
Mazda RX4 Wag     21.0   6  160 110 3.90 2.875 17.02  0  1
Datsun 710        22.8   4  108  93 3.85 2.320 18.61  1  1
Hornet 4 Drive    21.4   6  258 110 3.08 3.215 19.44  1  0
Hornet Sportabout 18.7   8  360 175 3.15 3.440 17.02  0  0
Valiant           18.1   6  225 105 2.76 3.460 20.22  1  0
                  gear carb
Mazda RX4            4    4
Mazda RX4 Wag        4    4
Datsun 710           4    1
Hornet 4 Drive       3    1
Hornet Sportabout    3    2
Valiant              3    1


> tail(car)
                mpg cyl  disp  hp drat    wt qsec vs am gear
Porsche 914-2  26.0   4 120.3  91 4.43 2.140 16.7  0  1    5
Lotus Europa   30.4   4  95.1 113 3.77 1.513 16.9  1  1    5
Ford Pantera L 15.8   8 351.0 264 4.22 3.170 14.5  0  1    5
Ferrari Dino   19.7   6 145.0 175 3.62 2.770 15.5  0  1    5
Maserati Bora  15.0   8 301.0 335 3.54 3.570 14.6  0  1    5
Volvo 142E     21.4   4 121.0 109 4.11 2.780 18.6  1  1    4
               carb
Porsche 914-2     2
Lotus Europa      2
Ford Pantera L    4
Ferrari Dino      6
Maserati Bora     8
Volvo 142E        2

> 

> summary(car)
      mpg             cyl             disp      
 Min.   :10.40   Min.   :4.000   Min.   : 71.1  
 1st Qu.:15.43   1st Qu.:4.000   1st Qu.:120.8  
 Median :19.20   Median :6.000   Median :196.3  
 Mean   :20.09   Mean   :6.188   Mean   :230.7  
 3rd Qu.:22.80   3rd Qu.:8.000   3rd Qu.:326.0  
 Max.   :33.90   Max.   :8.000   Max.   :472.0  
       hp             drat             wt       
 Min.   : 52.0   Min.   :2.760   Min.   :1.513  
 1st Qu.: 96.5   1st Qu.:3.080   1st Qu.:2.581  
 Median :123.0   Median :3.695   Median :3.325  
 Mean   :146.7   Mean   :3.597   Mean   :3.217  
 3rd Qu.:180.0   3rd Qu.:3.920   3rd Qu.:3.610  
 Max.   :335.0   Max.   :4.930   Max.   :5.424  
      qsec             vs               am        
 Min.   :14.50   Min.   :0.0000   Min.   :0.0000  
 1st Qu.:16.89   1st Qu.:0.0000   1st Qu.:0.0000  
 Median :17.71   Median :0.0000   Median :0.0000  
 Mean   :17.85   Mean   :0.4375   Mean   :0.4062  
 3rd Qu.:18.90   3rd Qu.:1.0000   3rd Qu.:1.0000  
 Max.   :22.90   Max.   :1.0000   Max.   :1.0000  
      gear            carb      
 Min.   :3.000   Min.   :1.000  
 1st Qu.:3.000   1st Qu.:2.000  
 Median :4.000   Median :2.000  
 Mean   :3.688   Mean   :2.812  
 3rd Qu.:4.000   3rd Qu.:4.000  
 Max.   :5.000   Max.   :8.000  


> str(car)
'data.frame':	32 obs. of  11 variables:
 $ mpg : num  21 21 22.8 21.4 18.7 18.1 14.3 24.4 22.8 19.2 ...
 $ cyl : num  6 6 4 6 8 6 8 4 4 6 ...
 $ disp: num  160 160 108 258 360 ...
 $ hp  : num  110 110 93 110 175 105 245 62 95 123 ...
 $ drat: num  3.9 3.9 3.85 3.08 3.15 2.76 3.21 3.69 3.92 3.92 ...
 $ wt  : num  2.62 2.88 2.32 3.21 3.44 ...
 $ qsec: num  16.5 17 18.6 19.4 17 ...
 $ vs  : num  0 0 1 1 0 1 0 1 1 1 ...
 $ am  : num  1 1 1 0 0 0 0 0 0 0 ...
 $ gear: num  4 4 4 3 3 3 3 4 4 4 ...
 $ carb: num  4 4 1 1 2 1 4 2 2 4 ...


> glimpse(car)
Observations: 32
Variables: 11
$ mpg  <dbl> 21.0, 21.0, 22.8, 21.4, 18.7, 18.1, 14.3, 2...
$ cyl  <dbl> 6, 6, 4, 6, 8, 6, 8, 4, 4, 6, 6, 8, 8, 8, 8...
$ disp <dbl> 160.0, 160.0, 108.0, 258.0, 360.0, 225.0, 3...
$ hp   <dbl> 110, 110, 93, 110, 175, 105, 245, 62, 95, 1...
$ drat <dbl> 3.90, 3.90, 3.85, 3.08, 3.15, 2.76, 3.21, 3...
$ wt   <dbl> 2.620, 2.875, 2.320, 3.215, 3.440, 3.460, 3...
$ qsec <dbl> 16.46, 17.02, 18.61, 19.44, 17.02, 20.22, 1...
$ vs   <dbl> 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0...
$ am   <dbl> 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0...
$ gear <dbl> 4, 4, 4, 3, 3, 3, 3, 4, 4, 4, 4, 3, 3, 3, 3...
$ carb <dbl> 4, 4, 1, 1, 2, 1, 4, 2, 2, 4, 4, 3, 3, 3, 4...

> 

> nrow(car)
[1] 32


> ncol(car)
[1] 11


> dim(car)
[1] 32 11


> colnames(car)
 [1] "mpg"  "cyl"  "disp" "hp"   "drat" "wt"   "qsec" "vs"  
 [9] "am"   "gear" "carb"


> rownames(car)
 [1] "Mazda RX4"           "Mazda RX4 Wag"      
 [3] "Datsun 710"          "Hornet 4 Drive"     
 [5] "Hornet Sportabout"   "Valiant"            
 [7] "Duster 360"          "Merc 240D"          
 [9] "Merc 230"            "Merc 280"           
[11] "Merc 280C"           "Merc 450SE"         
[13] "Merc 450SL"          "Merc 450SLC"        
[15] "Cadillac Fleetwood"  "Lincoln Continental"
[17] "Chrysler Imperial"   "Fiat 128"           
[19] "Honda Civic"         "Toyota Corolla"     
[21] "Toyota Corona"       "Dodge Challenger"   
[23] "AMC Javelin"         "Camaro Z28"         
[25] "Pontiac Firebird"    "Fiat X1-9"          
[27] "Porsche 914-2"       "Lotus Europa"       
[29] "Ford Pantera L"      "Ferrari Dino"       
[31] "Maserati Bora"       "Volvo 142E"         

> 

> cbind(car, car, car)
                     mpg cyl  disp  hp drat    wt  qsec vs
Mazda RX4           21.0   6 160.0 110 3.90 2.620 16.46  0
Mazda RX4 Wag       21.0   6 160.0 110 3.90 2.875 17.02  0
Datsun 710          22.8   4 108.0  93 3.85 2.320 18.61  1
Hornet 4 Drive      21.4   6 258.0 110 3.08 3.215 19.44  1
Hornet Sportabout   18.7   8 360.0 175 3.15 3.440 17.02  0
Valiant             18.1   6 225.0 105 2.76 3.460 20.22  1
Duster 360          14.3   8 360.0 245 3.21 3.570 15.84  0
Merc 240D           24.4   4 146.7  62 3.69 3.190 20.00  1
Merc 230            22.8   4 140.8  95 3.92 3.150 22.90  1
Merc 280            19.2   6 167.6 123 3.92 3.440 18.30  1
Merc 280C           17.8   6 167.6 123 3.92 3.440 18.90  1
Merc 450SE          16.4   8 275.8 180 3.07 4.070 17.40  0
Merc 450SL          17.3   8 275.8 180 3.07 3.730 17.60  0
Merc 450SLC         15.2   8 275.8 180 3.07 3.780 18.00  0
Cadillac Fleetwood  10.4   8 472.0 205 2.93 5.250 17.98  0
Lincoln Continental 10.4   8 460.0 215 3.00 5.424 17.82  0
Chrysler Imperial   14.7   8 440.0 230 3.23 5.345 17.42  0
Fiat 128            32.4   4  78.7  66 4.08 2.200 19.47  1
Honda Civic         30.4   4  75.7  52 4.93 1.615 18.52  1
Toyota Corolla      33.9   4  71.1  65 4.22 1.835 19.90  1
Toyota Corona       21.5   4 120.1  97 3.70 2.465 20.01  1
Dodge Challenger    15.5   8 318.0 150 2.76 3.520 16.87  0
AMC Javelin         15.2   8 304.0 150 3.15 3.435 17.30  0
Camaro Z28          13.3   8 350.0 245 3.73 3.840 15.41  0
Pontiac Firebird    19.2   8 400.0 175 3.08 3.845 17.05  0
Fiat X1-9           27.3   4  79.0  66 4.08 1.935 18.90  1
Porsche 914-2       26.0   4 120.3  91 4.43 2.140 16.70  0
Lotus Europa        30.4   4  95.1 113 3.77 1.513 16.90  1
Ford Pantera L      15.8   8 351.0 264 4.22 3.170 14.50  0
Ferrari Dino        19.7   6 145.0 175 3.62 2.770 15.50  0
                    am gear carb  mpg cyl  disp  hp drat
Mazda RX4            1    4    4 21.0   6 160.0 110 3.90
Mazda RX4 Wag        1    4    4 21.0   6 160.0 110 3.90
Datsun 710           1    4    1 22.8   4 108.0  93 3.85
Hornet 4 Drive       0    3    1 21.4   6 258.0 110 3.08
Hornet Sportabout    0    3    2 18.7   8 360.0 175 3.15
Valiant              0    3    1 18.1   6 225.0 105 2.76
Duster 360           0    3    4 14.3   8 360.0 245 3.21
Merc 240D            0    4    2 24.4   4 146.7  62 3.69
Merc 230             0    4    2 22.8   4 140.8  95 3.92
Merc 280             0    4    4 19.2   6 167.6 123 3.92
Merc 280C            0    4    4 17.8   6 167.6 123 3.92
Merc 450SE           0    3    3 16.4   8 275.8 180 3.07
Merc 450SL           0    3    3 17.3   8 275.8 180 3.07
Merc 450SLC          0    3    3 15.2   8 275.8 180 3.07
Cadillac Fleetwood   0    3    4 10.4   8 472.0 205 2.93
Lincoln Continental  0    3    4 10.4   8 460.0 215 3.00
Chrysler Imperial    0    3    4 14.7   8 440.0 230 3.23
Fiat 128             1    4    1 32.4   4  78.7  66 4.08
Honda Civic          1    4    2 30.4   4  75.7  52 4.93
Toyota Corolla       1    4    1 33.9   4  71.1  65 4.22
Toyota Corona        0    3    1 21.5   4 120.1  97 3.70
Dodge Challenger     0    3    2 15.5   8 318.0 150 2.76
AMC Javelin          0    3    2 15.2   8 304.0 150 3.15
Camaro Z28           0    3    4 13.3   8 350.0 245 3.73
Pontiac Firebird     0    3    2 19.2   8 400.0 175 3.08
Fiat X1-9            1    4    1 27.3   4  79.0  66 4.08
Porsche 914-2        1    5    2 26.0   4 120.3  91 4.43
Lotus Europa         1    5    2 30.4   4  95.1 113 3.77
Ford Pantera L       1    5    4 15.8   8 351.0 264 4.22
Ferrari Dino         1    5    6 19.7   6 145.0 175 3.62
                       wt  qsec vs am gear carb  mpg cyl
Mazda RX4           2.620 16.46  0  1    4    4 21.0   6
Mazda RX4 Wag       2.875 17.02  0  1    4    4 21.0   6
Datsun 710          2.320 18.61  1  1    4    1 22.8   4
Hornet 4 Drive      3.215 19.44  1  0    3    1 21.4   6
Hornet Sportabout   3.440 17.02  0  0    3    2 18.7   8
Valiant             3.460 20.22  1  0    3    1 18.1   6
Duster 360          3.570 15.84  0  0    3    4 14.3   8
Merc 240D           3.190 20.00  1  0    4    2 24.4   4
Merc 230            3.150 22.90  1  0    4    2 22.8   4
Merc 280            3.440 18.30  1  0    4    4 19.2   6
Merc 280C           3.440 18.90  1  0    4    4 17.8   6
Merc 450SE          4.070 17.40  0  0    3    3 16.4   8
Merc 450SL          3.730 17.60  0  0    3    3 17.3   8
Merc 450SLC         3.780 18.00  0  0    3    3 15.2   8
Cadillac Fleetwood  5.250 17.98  0  0    3    4 10.4   8
Lincoln Continental 5.424 17.82  0  0    3    4 10.4   8
Chrysler Imperial   5.345 17.42  0  0    3    4 14.7   8
Fiat 128            2.200 19.47  1  1    4    1 32.4   4
Honda Civic         1.615 18.52  1  1    4    2 30.4   4
Toyota Corolla      1.835 19.90  1  1    4    1 33.9   4
Toyota Corona       2.465 20.01  1  0    3    1 21.5   4
Dodge Challenger    3.520 16.87  0  0    3    2 15.5   8
AMC Javelin         3.435 17.30  0  0    3    2 15.2   8
Camaro Z28          3.840 15.41  0  0    3    4 13.3   8
Pontiac Firebird    3.845 17.05  0  0    3    2 19.2   8
Fiat X1-9           1.935 18.90  1  1    4    1 27.3   4
Porsche 914-2       2.140 16.70  0  1    5    2 26.0   4
Lotus Europa        1.513 16.90  1  1    5    2 30.4   4
Ford Pantera L      3.170 14.50  0  1    5    4 15.8   8
Ferrari Dino        2.770 15.50  0  1    5    6 19.7   6
                     disp  hp drat    wt  qsec vs am gear
Mazda RX4           160.0 110 3.90 2.620 16.46  0  1    4
Mazda RX4 Wag       160.0 110 3.90 2.875 17.02  0  1    4
Datsun 710          108.0  93 3.85 2.320 18.61  1  1    4
Hornet 4 Drive      258.0 110 3.08 3.215 19.44  1  0    3
Hornet Sportabout   360.0 175 3.15 3.440 17.02  0  0    3
Valiant             225.0 105 2.76 3.460 20.22  1  0    3
Duster 360          360.0 245 3.21 3.570 15.84  0  0    3
Merc 240D           146.7  62 3.69 3.190 20.00  1  0    4
Merc 230            140.8  95 3.92 3.150 22.90  1  0    4
Merc 280            167.6 123 3.92 3.440 18.30  1  0    4
Merc 280C           167.6 123 3.92 3.440 18.90  1  0    4
Merc 450SE          275.8 180 3.07 4.070 17.40  0  0    3
Merc 450SL          275.8 180 3.07 3.730 17.60  0  0    3
Merc 450SLC         275.8 180 3.07 3.780 18.00  0  0    3
Cadillac Fleetwood  472.0 205 2.93 5.250 17.98  0  0    3
Lincoln Continental 460.0 215 3.00 5.424 17.82  0  0    3
Chrysler Imperial   440.0 230 3.23 5.345 17.42  0  0    3
Fiat 128             78.7  66 4.08 2.200 19.47  1  1    4
Honda Civic          75.7  52 4.93 1.615 18.52  1  1    4
Toyota Corolla       71.1  65 4.22 1.835 19.90  1  1    4
Toyota Corona       120.1  97 3.70 2.465 20.01  1  0    3
Dodge Challenger    318.0 150 2.76 3.520 16.87  0  0    3
AMC Javelin         304.0 150 3.15 3.435 17.30  0  0    3
Camaro Z28          350.0 245 3.73 3.840 15.41  0  0    3
Pontiac Firebird    400.0 175 3.08 3.845 17.05  0  0    3
Fiat X1-9            79.0  66 4.08 1.935 18.90  1  1    4
Porsche 914-2       120.3  91 4.43 2.140 16.70  0  1    5
Lotus Europa         95.1 113 3.77 1.513 16.90  1  1    5
Ford Pantera L      351.0 264 4.22 3.170 14.50  0  1    5
Ferrari Dino        145.0 175 3.62 2.770 15.50  0  1    5
                    carb
Mazda RX4              4
Mazda RX4 Wag          4
Datsun 710             1
Hornet 4 Drive         1
Hornet Sportabout      2
Valiant                1
Duster 360             4
Merc 240D              2
Merc 230               2
Merc 280               4
Merc 280C              4
Merc 450SE             3
Merc 450SL             3
Merc 450SLC            3
Cadillac Fleetwood     4
Lincoln Continental    4
Chrysler Imperial      4
Fiat 128               1
Honda Civic            2
Toyota Corolla         1
Toyota Corona          1
Dodge Challenger       2
AMC Javelin            2
Camaro Z28             4
Pontiac Firebird       2
Fiat X1-9              1
Porsche 914-2          2
Lotus Europa           2
Ford Pantera L         4
Ferrari Dino           6
 [ reached getOption("max.print") -- omitted 2 rows ]


> rbind(car, car, car)
                      mpg cyl  disp  hp drat    wt  qsec vs
Mazda RX4            21.0   6 160.0 110 3.90 2.620 16.46  0
Mazda RX4 Wag        21.0   6 160.0 110 3.90 2.875 17.02  0
Datsun 710           22.8   4 108.0  93 3.85 2.320 18.61  1
Hornet 4 Drive       21.4   6 258.0 110 3.08 3.215 19.44  1
Hornet Sportabout    18.7   8 360.0 175 3.15 3.440 17.02  0
Valiant              18.1   6 225.0 105 2.76 3.460 20.22  1
Duster 360           14.3   8 360.0 245 3.21 3.570 15.84  0
Merc 240D            24.4   4 146.7  62 3.69 3.190 20.00  1
Merc 230             22.8   4 140.8  95 3.92 3.150 22.90  1
Merc 280             19.2   6 167.6 123 3.92 3.440 18.30  1
Merc 280C            17.8   6 167.6 123 3.92 3.440 18.90  1
Merc 450SE           16.4   8 275.8 180 3.07 4.070 17.40  0
Merc 450SL           17.3   8 275.8 180 3.07 3.730 17.60  0
Merc 450SLC          15.2   8 275.8 180 3.07 3.780 18.00  0
Cadillac Fleetwood   10.4   8 472.0 205 2.93 5.250 17.98  0
Lincoln Continental  10.4   8 460.0 215 3.00 5.424 17.82  0
Chrysler Imperial    14.7   8 440.0 230 3.23 5.345 17.42  0
Fiat 128             32.4   4  78.7  66 4.08 2.200 19.47  1
Honda Civic          30.4   4  75.7  52 4.93 1.615 18.52  1
Toyota Corolla       33.9   4  71.1  65 4.22 1.835 19.90  1
Toyota Corona        21.5   4 120.1  97 3.70 2.465 20.01  1
Dodge Challenger     15.5   8 318.0 150 2.76 3.520 16.87  0
AMC Javelin          15.2   8 304.0 150 3.15 3.435 17.30  0
Camaro Z28           13.3   8 350.0 245 3.73 3.840 15.41  0
Pontiac Firebird     19.2   8 400.0 175 3.08 3.845 17.05  0
Fiat X1-9            27.3   4  79.0  66 4.08 1.935 18.90  1
Porsche 914-2        26.0   4 120.3  91 4.43 2.140 16.70  0
Lotus Europa         30.4   4  95.1 113 3.77 1.513 16.90  1
Ford Pantera L       15.8   8 351.0 264 4.22 3.170 14.50  0
Ferrari Dino         19.7   6 145.0 175 3.62 2.770 15.50  0
Maserati Bora        15.0   8 301.0 335 3.54 3.570 14.60  0
Volvo 142E           21.4   4 121.0 109 4.11 2.780 18.60  1
Mazda RX41           21.0   6 160.0 110 3.90 2.620 16.46  0
Mazda RX4 Wag1       21.0   6 160.0 110 3.90 2.875 17.02  0
Datsun 7101          22.8   4 108.0  93 3.85 2.320 18.61  1
Hornet 4 Drive1      21.4   6 258.0 110 3.08 3.215 19.44  1
Hornet Sportabout1   18.7   8 360.0 175 3.15 3.440 17.02  0
Valiant1             18.1   6 225.0 105 2.76 3.460 20.22  1
Duster 3601          14.3   8 360.0 245 3.21 3.570 15.84  0
Merc 240D1           24.4   4 146.7  62 3.69 3.190 20.00  1
Merc 2301            22.8   4 140.8  95 3.92 3.150 22.90  1
Merc 2801            19.2   6 167.6 123 3.92 3.440 18.30  1
Merc 280C1           17.8   6 167.6 123 3.92 3.440 18.90  1
Merc 450SE1          16.4   8 275.8 180 3.07 4.070 17.40  0
Merc 450SL1          17.3   8 275.8 180 3.07 3.730 17.60  0
Merc 450SLC1         15.2   8 275.8 180 3.07 3.780 18.00  0
Cadillac Fleetwood1  10.4   8 472.0 205 2.93 5.250 17.98  0
Lincoln Continental1 10.4   8 460.0 215 3.00 5.424 17.82  0
Chrysler Imperial1   14.7   8 440.0 230 3.23 5.345 17.42  0
Fiat 1281            32.4   4  78.7  66 4.08 2.200 19.47  1
Honda Civic1         30.4   4  75.7  52 4.93 1.615 18.52  1
Toyota Corolla1      33.9   4  71.1  65 4.22 1.835 19.90  1
Toyota Corona1       21.5   4 120.1  97 3.70 2.465 20.01  1
Dodge Challenger1    15.5   8 318.0 150 2.76 3.520 16.87  0
AMC Javelin1         15.2   8 304.0 150 3.15 3.435 17.30  0
Camaro Z281          13.3   8 350.0 245 3.73 3.840 15.41  0
Pontiac Firebird1    19.2   8 400.0 175 3.08 3.845 17.05  0
Fiat X1-91           27.3   4  79.0  66 4.08 1.935 18.90  1
Porsche 914-21       26.0   4 120.3  91 4.43 2.140 16.70  0
Lotus Europa1        30.4   4  95.1 113 3.77 1.513 16.90  1
Ford Pantera L1      15.8   8 351.0 264 4.22 3.170 14.50  0
Ferrari Dino1        19.7   6 145.0 175 3.62 2.770 15.50  0
Maserati Bora1       15.0   8 301.0 335 3.54 3.570 14.60  0
Volvo 142E1          21.4   4 121.0 109 4.11 2.780 18.60  1
Mazda RX42           21.0   6 160.0 110 3.90 2.620 16.46  0
Mazda RX4 Wag2       21.0   6 160.0 110 3.90 2.875 17.02  0
Datsun 7102          22.8   4 108.0  93 3.85 2.320 18.61  1
Hornet 4 Drive2      21.4   6 258.0 110 3.08 3.215 19.44  1
Hornet Sportabout2   18.7   8 360.0 175 3.15 3.440 17.02  0
Valiant2             18.1   6 225.0 105 2.76 3.460 20.22  1
Duster 3602          14.3   8 360.0 245 3.21 3.570 15.84  0
Merc 240D2           24.4   4 146.7  62 3.69 3.190 20.00  1
Merc 2302            22.8   4 140.8  95 3.92 3.150 22.90  1
Merc 2802            19.2   6 167.6 123 3.92 3.440 18.30  1
Merc 280C2           17.8   6 167.6 123 3.92 3.440 18.90  1
Merc 450SE2          16.4   8 275.8 180 3.07 4.070 17.40  0
Merc 450SL2          17.3   8 275.8 180 3.07 3.730 17.60  0
Merc 450SLC2         15.2   8 275.8 180 3.07 3.780 18.00  0
Cadillac Fleetwood2  10.4   8 472.0 205 2.93 5.250 17.98  0
Lincoln Continental2 10.4   8 460.0 215 3.00 5.424 17.82  0
Chrysler Imperial2   14.7   8 440.0 230 3.23 5.345 17.42  0
Fiat 1282            32.4   4  78.7  66 4.08 2.200 19.47  1
Honda Civic2         30.4   4  75.7  52 4.93 1.615 18.52  1
Toyota Corolla2      33.9   4  71.1  65 4.22 1.835 19.90  1
Toyota Corona2       21.5   4 120.1  97 3.70 2.465 20.01  1
Dodge Challenger2    15.5   8 318.0 150 2.76 3.520 16.87  0
AMC Javelin2         15.2   8 304.0 150 3.15 3.435 17.30  0
Camaro Z282          13.3   8 350.0 245 3.73 3.840 15.41  0
Pontiac Firebird2    19.2   8 400.0 175 3.08 3.845 17.05  0
Fiat X1-92           27.3   4  79.0  66 4.08 1.935 18.90  1
                     am gear carb
Mazda RX4             1    4    4
Mazda RX4 Wag         1    4    4
Datsun 710            1    4    1
Hornet 4 Drive        0    3    1
Hornet Sportabout     0    3    2
Valiant               0    3    1
Duster 360            0    3    4
Merc 240D             0    4    2
Merc 230              0    4    2
Merc 280              0    4    4
Merc 280C             0    4    4
Merc 450SE            0    3    3
Merc 450SL            0    3    3
Merc 450SLC           0    3    3
Cadillac Fleetwood    0    3    4
Lincoln Continental   0    3    4
Chrysler Imperial     0    3    4
Fiat 128              1    4    1
Honda Civic           1    4    2
Toyota Corolla        1    4    1
Toyota Corona         0    3    1
Dodge Challenger      0    3    2
AMC Javelin           0    3    2
Camaro Z28            0    3    4
Pontiac Firebird      0    3    2
Fiat X1-9             1    4    1
Porsche 914-2         1    5    2
Lotus Europa          1    5    2
Ford Pantera L        1    5    4
Ferrari Dino          1    5    6
Maserati Bora         1    5    8
Volvo 142E            1    4    2
Mazda RX41            1    4    4
Mazda RX4 Wag1        1    4    4
Datsun 7101           1    4    1
Hornet 4 Drive1       0    3    1
Hornet Sportabout1    0    3    2
Valiant1              0    3    1
Duster 3601           0    3    4
Merc 240D1            0    4    2
Merc 2301             0    4    2
Merc 2801             0    4    4
Merc 280C1            0    4    4
Merc 450SE1           0    3    3
Merc 450SL1           0    3    3
Merc 450SLC1          0    3    3
Cadillac Fleetwood1   0    3    4
Lincoln Continental1  0    3    4
Chrysler Imperial1    0    3    4
Fiat 1281             1    4    1
Honda Civic1          1    4    2
Toyota Corolla1       1    4    1
Toyota Corona1        0    3    1
Dodge Challenger1     0    3    2
AMC Javelin1          0    3    2
Camaro Z281           0    3    4
Pontiac Firebird1     0    3    2
Fiat X1-91            1    4    1
Porsche 914-21        1    5    2
Lotus Europa1         1    5    2
Ford Pantera L1       1    5    4
Ferrari Dino1         1    5    6
Maserati Bora1        1    5    8
Volvo 142E1           1    4    2
Mazda RX42            1    4    4
Mazda RX4 Wag2        1    4    4
Datsun 7102           1    4    1
Hornet 4 Drive2       0    3    1
Hornet Sportabout2    0    3    2
Valiant2              0    3    1
Duster 3602           0    3    4
Merc 240D2            0    4    2
Merc 2302             0    4    2
Merc 2802             0    4    4
Merc 280C2            0    4    4
Merc 450SE2           0    3    3
Merc 450SL2           0    3    3
Merc 450SLC2          0    3    3
Cadillac Fleetwood2   0    3    4
Lincoln Continental2  0    3    4
Chrysler Imperial2    0    3    4
Fiat 1282             1    4    1
Honda Civic2          1    4    2
Toyota Corolla2       1    4    1
Toyota Corona2        0    3    1
Dodge Challenger2     0    3    2
AMC Javelin2          0    3    2
Camaro Z282           0    3    4
Pontiac Firebird2     0    3    2
Fiat X1-92            1    4    1
 [ reached getOption("max.print") -- omitted 6 rows ]

> 

> fix(car)

> help(car)
No documentation for ‘car’ in specified packages and libraries:
you could try ‘??car’

> 

> car$mpg
 [1] 21.0 21.0 22.8 21.4 18.7 18.1 14.3 24.4 22.8 19.2 17.8
[12] 16.4 17.3 15.2 10.4 10.4 14.7 32.4 30.4 33.9 21.5 15.5
[23] 15.2 13.3 19.2 27.3 26.0 30.4 15.8 19.7 15.0 21.4

> hp <- car$hp

> 

> car[car$disp > 235, ]
                     mpg cyl  disp  hp drat    wt  qsec vs
Hornet 4 Drive      21.4   6 258.0 110 3.08 3.215 19.44  1
Hornet Sportabout   18.7   8 360.0 175 3.15 3.440 17.02  0
Duster 360          14.3   8 360.0 245 3.21 3.570 15.84  0
Merc 450SE          16.4   8 275.8 180 3.07 4.070 17.40  0
Merc 450SL          17.3   8 275.8 180 3.07 3.730 17.60  0
Merc 450SLC         15.2   8 275.8 180 3.07 3.780 18.00  0
Cadillac Fleetwood  10.4   8 472.0 205 2.93 5.250 17.98  0
Lincoln Continental 10.4   8 460.0 215 3.00 5.424 17.82  0
Chrysler Imperial   14.7   8 440.0 230 3.23 5.345 17.42  0
Dodge Challenger    15.5   8 318.0 150 2.76 3.520 16.87  0
AMC Javelin         15.2   8 304.0 150 3.15 3.435 17.30  0
Camaro Z28          13.3   8 350.0 245 3.73 3.840 15.41  0
Pontiac Firebird    19.2   8 400.0 175 3.08 3.845 17.05  0
Ford Pantera L      15.8   8 351.0 264 4.22 3.170 14.50  0
Maserati Bora       15.0   8 301.0 335 3.54 3.570 14.60  0
                    am gear carb
Hornet 4 Drive       0    3    1
Hornet Sportabout    0    3    2
Duster 360           0    3    4
Merc 450SE           0    3    3
Merc 450SL           0    3    3
Merc 450SLC          0    3    3
Cadillac Fleetwood   0    3    4
Lincoln Continental  0    3    4
Chrysler Imperial    0    3    4
Dodge Challenger     0    3    2
AMC Javelin          0    3    2
Camaro Z28           0    3    4
Pontiac Firebird     0    3    2
Ford Pantera L       1    5    4
Maserati Bora        1    5    8


> car[car$disp > mean(car$disp), ]
                     mpg cyl  disp  hp drat    wt  qsec vs
Hornet 4 Drive      21.4   6 258.0 110 3.08 3.215 19.44  1
Hornet Sportabout   18.7   8 360.0 175 3.15 3.440 17.02  0
Duster 360          14.3   8 360.0 245 3.21 3.570 15.84  0
Merc 450SE          16.4   8 275.8 180 3.07 4.070 17.40  0
Merc 450SL          17.3   8 275.8 180 3.07 3.730 17.60  0
Merc 450SLC         15.2   8 275.8 180 3.07 3.780 18.00  0
Cadillac Fleetwood  10.4   8 472.0 205 2.93 5.250 17.98  0
Lincoln Continental 10.4   8 460.0 215 3.00 5.424 17.82  0
Chrysler Imperial   14.7   8 440.0 230 3.23 5.345 17.42  0
Dodge Challenger    15.5   8 318.0 150 2.76 3.520 16.87  0
AMC Javelin         15.2   8 304.0 150 3.15 3.435 17.30  0
Camaro Z28          13.3   8 350.0 245 3.73 3.840 15.41  0
Pontiac Firebird    19.2   8 400.0 175 3.08 3.845 17.05  0
Ford Pantera L      15.8   8 351.0 264 4.22 3.170 14.50  0
Maserati Bora       15.0   8 301.0 335 3.54 3.570 14.60  0
                    am gear carb
Hornet 4 Drive       0    3    1
Hornet Sportabout    0    3    2
Duster 360           0    3    4
Merc 450SE           0    3    3
Merc 450SL           0    3    3
Merc 450SLC          0    3    3
Cadillac Fleetwood   0    3    4
Lincoln Continental  0    3    4
Chrysler Imperial    0    3    4
Dodge Challenger     0    3    2
AMC Javelin          0    3    2
Camaro Z28           0    3    4
Pontiac Firebird     0    3    2
Ford Pantera L       1    5    4
Maserati Bora        1    5    8


> car[car$disp > mean(car$disp) & (car$hp > 180), ]
                     mpg cyl disp  hp drat    wt  qsec vs am
Duster 360          14.3   8  360 245 3.21 3.570 15.84  0  0
Cadillac Fleetwood  10.4   8  472 205 2.93 5.250 17.98  0  0
Lincoln Continental 10.4   8  460 215 3.00 5.424 17.82  0  0
Chrysler Imperial   14.7   8  440 230 3.23 5.345 17.42  0  0
Camaro Z28          13.3   8  350 245 3.73 3.840 15.41  0  0
Ford Pantera L      15.8   8  351 264 4.22 3.170 14.50  0  1
Maserati Bora       15.0   8  301 335 3.54 3.570 14.60  0  1
                    gear carb
Duster 360             3    4
Cadillac Fleetwood     3    4
Lincoln Continental    3    4
Chrysler Imperial      3    4
Camaro Z28             3    4
Ford Pantera L         5    4
Maserati Bora          5    8

Here is the Data Editor that should have appeared when you typed ' fix(car) '. To change any element, simply double click on a cell to change it.

<img src="http://i65.tinypic.com/29qefm0.png" border="0" alt="Image and video hosting by TinyPic"></a>

### Excercises:

Now that you've had time to play around with functions to deal with data frames, let's work backwards.

In [ ]:
> car 
                     mpg cyl  disp  hp drat    wt  qsec vs
Mazda RX4           21.0   6 160.0 110 3.90 2.620 16.46  0
Mazda RX4 Wag       21.0   6 160.0 110 3.90 2.875 17.02  0
Datsun 710          22.8   4 108.0  93 3.85 2.320 18.61  1
Hornet 4 Drive      21.4   6 258.0 110 3.08 3.215 19.44  1
Hornet Sportabout   18.7   8 360.0 175 3.15 3.440 17.02  0
Valiant             18.1   6 225.0 105 2.76 3.460 20.22  1
Duster 360          14.3   8 360.0 245 3.21 3.570 15.84  0
Merc 240D           24.4   4 146.7  62 3.69 3.190 20.00  1
Merc 230            22.8   4 140.8  95 3.92 3.150 22.90  1
Merc 280            19.2   6 167.6 123 3.92 3.440 18.30  1
Merc 280C           17.8   6 167.6 123 3.92 3.440 18.90  1
Merc 450SE          16.4   8 275.8 180 3.07 4.070 17.40  0
Merc 450SL          17.3   8 275.8 180 3.07 3.730 17.60  0
Merc 450SLC         15.2   8 275.8 180 3.07 3.780 18.00  0
Cadillac Fleetwood  10.4   8 472.0 205 2.93 5.250 17.98  0
Lincoln Continental 10.4   8 460.0 215 3.00 5.424 17.82  0
Chrysler Imperial   14.7   8 440.0 230 3.23 5.345 17.42  0
Fiat 128            32.4   4  78.7  66 4.08 2.200 19.47  1
Honda Civic         30.4   4  75.7  52 4.93 1.615 18.52  1
Toyota Corolla      33.9   4  71.1  65 4.22 1.835 19.90  1
Toyota Corona       21.5   4 120.1  97 3.70 2.465 20.01  1
Dodge Challenger    15.5   8 318.0 150 2.76 3.520 16.87  0
AMC Javelin         15.2   8 304.0 150 3.15 3.435 17.30  0
Camaro Z28          13.3   8 350.0 245 3.73 3.840 15.41  0
Pontiac Firebird    19.2   8 400.0 175 3.08 3.845 17.05  0
Fiat X1-9           27.3   4  79.0  66 4.08 1.935 18.90  1
Porsche 914-2       26.0   4 120.3  91 4.43 2.140 16.70  0
Lotus Europa        30.4   4  95.1 113 3.77 1.513 16.90  1
Ford Pantera L      15.8   8 351.0 264 4.22 3.170 14.50  0
Ferrari Dino        19.7   6 145.0 175 3.62 2.770 15.50  0
Maserati Bora       15.0   8 301.0 335 3.54 3.570 14.60  0
Volvo 142E          21.4   4 121.0 109 4.11 2.780 18.60  1
                    am gear carb
Mazda RX4            1    4    4
Mazda RX4 Wag        1    4    4
Datsun 710           1    4    1
Hornet 4 Drive       0    3    1
Hornet Sportabout    0    3    2
Valiant              0    3    1
Duster 360           0    3    4
Merc 240D            0    4    2
Merc 230             0    4    2
Merc 280             0    4    4
Merc 280C            0    4    4
Merc 450SE           0    3    3
Merc 450SL           0    3    3
Merc 450SLC          0    3    3
Cadillac Fleetwood   0    3    4
Lincoln Continental  0    3    4
Chrysler Imperial    0    3    4
Fiat 128             1    4    1
Honda Civic          1    4    2
Toyota Corolla       1    4    1
Toyota Corona        0    3    1
Dodge Challenger     0    3    2
AMC Javelin          0    3    2
Camaro Z28           0    3    4
Pontiac Firebird     0    3    2
Fiat X1-9            1    4    1
Porsche 914-2        1    5    2
Lotus Europa         1    5    2
Ford Pantera L       1    5    4
Ferrari Dino         1    5    6
Maserati Bora        1    5    8
Volvo 142E           1    4    2

**Question 1:**

Given the mtcars data frame above, subset the horsepower of the 3rd car and print the result.

In [ ]:
mtcars[[<FILL IN>]][<FILL IN>]

# Can you think of an alternative way of doing this?

**Question 2:**

Given the mtcars data frame above, subset all the headers of the first 10 cars and print the result.

In [ ]:
mtcars[[<FILL IN>]][<FILL IN>]

# Can you think of an alternative way of doing this?

**Question 3:**

Given the mtcars data frame above, subset all of the cars what have an mpg greater than 25.

In [ ]:
# Hint: if you need help, look in the example code for some inspiration.

### Now, if you're feelin' extra creative, go ahead and create your own data frames!

### If you're even MORE inspired to go the extra mile, go ahead and collect your own data! Maybe later, you'll be able to use that data after the data visualization tutorials to make some neat graphs!

## Congratulations!
You're done with tonight's exercises! Check back to [the syllabus](https://github.com/JasonFreeberg/R_Tutorials/blob/master/README.md) for this week's homework. 

If you haven't completed last week's homework, remember to do so to strengthen your understanding of the material!

**Suggested Homework:**
    - DataCamp: **Introduction** to R
        - Chapters 4 and 5: Factors and Dataframes
    - DataCamp: **Intermediate** R
        - Chapters 1 to 3: Contiditionals and Control Flow, Loops, and Functions